ViewModels/TopicViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace Task3.ViewModels
{
    public class TopicViewModel
    {
        public int Id { get; set; }
        public int? SectionId { get; set; }
        public SectionViewModel Section { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime Created { get; set; }
        public IdentityUser Creator { get; set; }
        public List<MessageViewModel> Messages { get; set; }
    }
}

Controllers/MessagesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task3.ViewModels;
using Task3.Store;
using Task3.Store.Models;
using Task3.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Task3.Controllers
{
    public class MessagesController : Controller
    {
        private IMessageService MessageService { get; }
        private ITopicService TopicService { get; }
        public MessagesController(IMessageService messageService, ITopicService topicService)
        {
            MessageService = messageService;
            TopicService = topicService;
        }
        public async Task<IActionResult> Index(int id)
        {
            try
            {
                var indexViewModel = await TopicService.GetViewModelAsync(id);
                return View(indexViewModel);
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }

        [Authorize]
        public async Task<IActionResult> Create(int id)
        {
            var model = await MessageService.GetCreateViewModelAsync(id);
            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MessageCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var createViewModel = await MessageService.GetCreateViewModelAsync(model.TopicId);
                return View(createViewModel);
            }
            try
            {
                await MessageService.CreateAsync(model, User);
                return RedirectToAction("Index", new { Id = model.TopicId });
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
            catch (InvalidDataException e)
            {
                ModelState.AddModelError(nameof(model.Attachments), e.Message);
                var createViewModel = await MessageService.GetCreateViewModelAsync(model.TopicId);
                return View(createViewModel);
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var editViewModel = await MessageService.GetEditViewModelAsync(id, User);
                return View(editViewModel);
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MessageEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await MessageService.EditAsync(model, User);
                return RedirectToAction("Index", new { Id = model.TopicId });
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var deleteViewModel = await MessageService.GetDeleteViewModelAsync(id, User);
                return View(deleteViewModel);
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(MessageDeleteViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await MessageService.DeleteAsync(model, User);
                return RedirectToAction("Index", new { Id = model.TopicId });
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }
    }
}

Controllers/SectionsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task3.ViewModels;
using Task3.Services;
using Microsoft.AspNetCore.Authorization;

namespace Task3.Controllers
{
    public class SectionsController : Controller
    {
        private ISectionService SectionService { get; }
        public SectionsController(ISectionService sectionService)
        {
            SectionService = sectionService;
        }
        public async Task<IActionResult> Index()
        {
            var model = await SectionService.GetIndexViewModelAsync();
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            var model = SectionService.GetCreateViewModel();
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SectionCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await SectionService.CreateAsync(model);
                return RedirectToAction("Index");
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError(nameof(model.Name), ae.Message);
                return View(model);
            }
        }

        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var model = await SectionService.GetEditViewModelAsync(id, User);
                return View(model);
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin, Moderator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SectionEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var editModel = await SectionService.GetEditViewModelAsync(model.Id, User);
                return View(editModel);
            }
            try
            {
                await SectionService.EditAsync(model, User);
                return RedirectToAction("Index");
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
            catch (ArgumentException ae)
            {
                ModelState.AddModelError(nameof(model.Name), ae.Message);
                var editViewModel = await SectionService.GetEditViewModelAsync(model.Id, User);
                return View(editViewModel);
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var model = await SectionService.GetDeleteViewModelAsync(id);
                return View(model);
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(SectionDeleteViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await SectionService.DeleteAsync(model);
                return RedirectToAction("Index");
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }
    }
}

Controllers/TopicsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Task3.ViewModels;
using Task3.Store;
using Task3.Store.Models;
using Task3.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Task3.Controllers
{
    public class TopicsController : Controller
    {
        private ITopicService TopicService { get; }
        private ISectionService SectionService { get; }
        public TopicsController(ITopicService topicService, ISectionService sectionService)
        {
            TopicService = topicService;
            SectionService = sectionService;
        }
        public async Task<IActionResult> Index(int id)
        {
            try
            {
                var indexViewModel = await SectionService.GetViewModelAsync(id);
                return View(indexViewModel);
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }

        [Authorize]
        public async Task<IActionResult> Create(int id)
        {
            var model = await TopicService.GetCreateViewModelAsync(id);
            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TopicCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var createModel = await TopicService.GetCreateViewModelAsync(model.SectionId);
                return View(createModel);
            }
            try
            {
                await TopicService.CreateAsync(model, User.Identity.Name);
                return RedirectToAction("Index", new { Id = model.SectionId });
            }
            catch(ArgumentNullException)
            {
                return NotFound();
            }

        }
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var editViewModel = await TopicService.GetEditViewModelAsync(id, User);
                return View(editViewModel);
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TopicEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var editModel = await TopicService.GetEditViewModelAsync(model.Id, User);
                return View(editModel);
            }
            try
            {
                await TopicService.EditAsync(model, User);
                return RedirectToAction("Index", new { Id = model.SectionId });
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var deleteViewModel = await TopicService.GetDeleteViewModelAsync(id, User);
                return View(deleteViewModel);
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(TopicDeleteViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var deleteModel = await TopicService.GetDeleteViewModelAsync(model.Id, User);
                return View(deleteModel);
            }
            try
            {
                await TopicService.DeleteAsync(model, User);
                return RedirectToAction("Index", new { Id = model.SectionId });
            }
            catch (ArgumentNullException)
            {
                return NotFound();
            }
        }
    }
}

Views/Topics/Create.cshtml
@model Task3.ViewModels.TopicCreateViewModel

<h1>Creating Topic for @Model.Section.Name</h1>

<form asp-action="Create" asp-controller="Topics" method="POST">
    <input type="hidden" asp-for="SectionId" />

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" type="text" class="form-control" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" type="text" class="form-control" />
    </div>

    <div class="flex-lg-row">
        <a asp-controller="Topics" asp-action="Index" asp-route-id="@Model.SectionId" class="btn btn-secondary">< Back</a>
        <button class="btn btn-success" type="submit">+ Create Topic</button>
    </div>
</form>

Views/Topics/Delete.cshtml
@model Task3.ViewModels.TopicDeleteViewModel

<h1>Are you sure you want to delete @Model.Name?</h1>
<form asp-action="Delete" asp-controller="Topics" method="POST">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="SectionId" />
    <div class="list-group">
        <div class="list-group-item d-flex justify-content-between">
            <div class="font-weight-bold">@Model.Name</div>
        </div>
        @if (!String.IsNullOrEmpty(Model.Description))
        {
            <div class="list-group-item">
                <div class="text-info">@Model.Description</div>
            </div>
        }
    </div>

    <hr>
    <div class="flex-lg-row">
        <a asp-controller="Topics" asp-action="Index" asp-route-id="@Model.SectionId" class="btn btn-secondary">< Back</a>
        <button class="btn btn-danger" type="submit">Delete Topic</button>
    </div>
</form>

Views/Topics/Edit.cshtml
@model Task3.ViewModels.TopicEditViewModel

<h1>Editing @Model.Name</h1>

<form asp-action="Edit" asp-controller="Topics" method="POST">
    <input type="hidden" asp-for="SectionId" />

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" type="text" class="form-control" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" type="text" class="form-control" />
    </div>

    <div class="flex-lg-row">
        <a asp-controller="Topics" asp-action="Index" asp-route-id="@Model.SectionId" class="btn btn-secondary">< Back</a>
        <button class="btn btn-primary" type="submit">Edit Topic</button>
    </div>
</form>

Views/Topics/Index.cshtml
@model Task3.ViewModels.SectionViewModel
@{
    ViewData["Title"] = "Forum Page";
}

<h1>@Model.Name</h1>
@Model.Description
<hr>
<div class="flex-lg-row">
    <a asp-controller="Sections" asp-action="Index" class="btn btn-secondary mb-3">< Back</a>
    <a asp-controller="Topics" asp-action="Create" asp-route-id=@Model.Id class="btn btn-success mb-3">+ Create Topic</a>
</div>

@if (Model.Topics.Any())
{
<div class="list-group">
    @foreach (var item in Model.Topics)
    {
    <div class="list-group-item d-flex flex-column">
        <div class="d-flex justify-content-between">
            <div class="flex-lg-row">
                <a class="font-weight-bold" asp-action="Index" asp-controller="Messages" asp-route-id="@item.Id">@item.Name</a>
                @if (item.Creator != null)
                {
                    <a class="text-info">
                        posted by @item.Creator.UserName at
                    </a>
                }
                <a>@item.Created</a>

            </div>
            <div class="justify-content-end">
                @if (((item.Creator != null) && (item.Creator.UserName == User.Identity.Name)) || (User.IsInRole("Admin")) || (User.IsInRole("Moderator")) && (item.Section.Moderators.Any(x => x.UserName == User.Identity.Name)))
                {
                    <div style="display: flex; gap: 10px;">
                        <a class="text-danger" asp-action="Delete" asp-controller="Topics" asp-route-id="@item.Id">Delete</a>
                        <a asp-action="Edit" asp-controller="Topics" asp-route-id="@item.Id">Edit</a>
                    </div>
                }
                </div>
        </div>

        @if (!String.IsNullOrEmpty(item.Description))
        {
            <div class="d-flex">
                <div class="text-secondary">@item.Description</div>
            </div>
        }
    </div>
    }
</div>
    }

    else
    {
    <div class="alert alert-info">
        Section empty.
    </div>
    }